-- =====================================================================
-- Prism 검사·재고 관리 — PostgreSQL 스키마 (SQLite 데이터모델 v2.2 이식)
-- "새 섹터" = prism 스키마에 생성. (기존 DB 안에 격리된 네임스페이스)
--
-- 사용법:
--   psql "postgresql://USER:PW@HOST:PORT/DBNAME" -f schema_postgres.sql
--   그 다음  psql "..." -f prism_data.sql   (sqlite_to_pg.py 로 생성)
--
-- 설계 메모:
--   * AUTOINCREMENT PK -> GENERATED BY DEFAULT AS IDENTITY (명시 id 입력 허용 → 원본 id/FK 보존)
--   * supplier.is_active(가상 생성열) -> GENERATED ALWAYS AS ... STORED
--   * 불리언은 원본과 동일하게 0/1 integer 유지(앱 코드 호환)
--   * FK/부분유니크는 데이터 적재 편의를 위해 테이블 생성 후 일괄 부여
-- =====================================================================

CREATE SCHEMA IF NOT EXISTS prism;
SET search_path TO prism, public;

-- ── 프리즘 마스터 ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS prism_master (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_code       text,
    prism_type      text NOT NULL CHECK (prism_type IN ('PLASTIC','GLASS')),
    model           text,
    spec            text,
    supplier_id     integer,
    paint_state     text NOT NULL DEFAULT 'NONE' CHECK (paint_state IN ('RAW','PAINTED','NONE')),
    painted_into_id integer,
    unit            text NOT NULL DEFAULT 'EA',
    is_active       integer NOT NULL DEFAULT 1,
    note            text,
    created_at      text NOT NULL,
    updated_at      text NOT NULL
);

-- ── 공급사 (is_active 는 status 파생 저장열) ────────────────
CREATE TABLE IF NOT EXISTS supplier (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         text NOT NULL UNIQUE,
    status       text NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','REMNANT','STOPPED')),
    is_active    integer GENERATED ALWAYS AS (CASE WHEN status='ACTIVE' THEN 1 ELSE 0 END) STORED,
    note         text,
    created_at   text NOT NULL,
    updated_at   text NOT NULL
);

-- ── 검사항목 마스터 ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS inspection_item (
    id                     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                   text NOT NULL UNIQUE,
    category               text,
    applies_to_incoming    integer NOT NULL DEFAULT 1,
    applies_to_post_paint  integer NOT NULL DEFAULT 1,
    sort_order             integer NOT NULL DEFAULT 0,
    is_active              integer NOT NULL DEFAULT 1,
    created_at             text NOT NULL,
    updated_at             text NOT NULL
);

-- ── 제품마스터(BOM) ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS product (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code    text NOT NULL UNIQUE,
    product_name    text,
    prism_id        integer,
    prism_per_unit  integer NOT NULL DEFAULT 1,
    is_active       integer NOT NULL DEFAULT 1,
    note            text,
    created_at      text NOT NULL,
    updated_at      text NOT NULL
);

-- ── 입고(헤더) ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS receipt (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_no       text NOT NULL UNIQUE,
    receipt_date     text NOT NULL,
    prism_id         integer NOT NULL,
    supplier_id      integer NOT NULL,
    received_qty     integer NOT NULL CHECK (received_qty > 0),
    supplier_lot_no  text,
    operator         text,
    note             text,
    created_at       text NOT NULL,
    updated_at       text NOT NULL
);

-- ── 로트 ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS lot (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id    integer NOT NULL,
    lot_no        text NOT NULL,
    lot_qty       integer NOT NULL CHECK (lot_qty > 0),
    split_reason  text,
    status        text NOT NULL DEFAULT 'CREATED'
                  CHECK (status IN ('CREATED','INCOMING_DONE','PAINTING','POST_PAINT_DONE','CLOSED')),
    created_at    text NOT NULL,
    updated_at    text NOT NULL,
    UNIQUE (receipt_id, lot_no)
);

-- ── 검사 ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS inspection (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lot_id         integer NOT NULL,
    stage          text NOT NULL CHECK (stage IN ('INCOMING','POST_PAINT')),
    method         text NOT NULL DEFAULT 'FULL' CHECK (method IN ('FULL','SAMPLING')),
    start_date     text,
    end_date       text,
    inspected_qty  integer NOT NULL DEFAULT 0,
    good_qty       integer NOT NULL DEFAULT 0,
    defect_qty     integer NOT NULL DEFAULT 0,
    sample_size    integer,
    accept_count   integer,
    reject_count   integer,
    aql_level      text,
    judgment       text CHECK (judgment IN ('PASS','FAIL','CONDITIONAL')),
    inspector      text,
    is_complete    integer NOT NULL DEFAULT 0,
    note           text,
    created_at     text NOT NULL,
    updated_at     text NOT NULL,
    UNIQUE (lot_id, stage)
);

-- ── 검사불량(롱포맷) ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS inspection_defect (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inspection_id       integer NOT NULL,
    inspection_item_id  integer NOT NULL,
    defect_qty          integer NOT NULL DEFAULT 0,
    UNIQUE (inspection_id, inspection_item_id)
);

-- ── 페인트 외주(발송) ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS paint_job (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lot_id       integer NOT NULL,
    vendor       text,
    sent_date    text NOT NULL,
    sent_qty     integer NOT NULL CHECK (sent_qty > 0),
    is_returned  integer NOT NULL DEFAULT 0,
    note         text,
    created_at   text NOT NULL,
    updated_at   text NOT NULL
);

-- ── 페인트 분할 회수 ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS paint_return (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paint_job_id   integer NOT NULL,
    returned_date  text NOT NULL,
    returned_qty   integer NOT NULL CHECK (returned_qty > 0),
    note           text,
    created_at     text NOT NULL
);

-- ── 구매/생산계획 ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS production_plan (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_month   text NOT NULL,
    source_file  text,
    is_final     integer NOT NULL DEFAULT 0,
    imported_at  text,
    note         text,
    created_at   text NOT NULL,
    updated_at   text NOT NULL
);

CREATE TABLE IF NOT EXISTS production_plan_line (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id       integer NOT NULL,
    product_code  text NOT NULL,
    planned_qty   integer NOT NULL DEFAULT 0,
    product_id    integer,
    prism_id      integer,
    consumed_qty  integer NOT NULL DEFAULT 0,
    note          text
);

-- ── 소비 원장 ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS consumption (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prism_id        integer NOT NULL,
    supplier_id     integer,
    source          text NOT NULL CHECK (source IN ('PLAN','MANUAL','ADJUST')),
    source_plan_id  integer,
    qty             integer NOT NULL,
    consumed_at     text NOT NULL,
    note            text,
    created_at      text NOT NULL
);

-- ── 재고 보정 ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS stock_adjustment (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prism_id     integer NOT NULL,
    qty          integer NOT NULL,
    reason       text NOT NULL DEFAULT 'OPENING' CHECK (reason IN ('OPENING','MANUAL')),
    adjusted_at  text NOT NULL,
    note         text,
    created_at   text NOT NULL
);

-- ── 사용불가(불량/보류) 재고 ─────────────────────────────────
-- 현재고에는 포함되나 실제 사용 불가한 수량(표시용). 가용 = 현재고 − 사용불가.
CREATE TABLE IF NOT EXISTS unusable_stock (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prism_id     integer NOT NULL,
    qty          integer NOT NULL,
    category     text NOT NULL DEFAULT '불량',
    dated        text NOT NULL,
    note         text,
    created_at   text NOT NULL
);

-- ── 도장완료 페인트후 불량(품목 레벨 일괄) ───────────────────
CREATE TABLE IF NOT EXISTS paint_batch (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prism_id      integer NOT NULL,
    batch_date    text NOT NULL,
    good_qty      integer NOT NULL DEFAULT 0,
    defect_qty    integer NOT NULL DEFAULT 0,
    note          text,
    created_at    text NOT NULL
);
CREATE TABLE IF NOT EXISTS paint_batch_defect (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id            integer NOT NULL,
    inspection_item_id  integer NOT NULL,
    defect_qty          integer NOT NULL DEFAULT 0
);

-- ── 행위/이력 로그 ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS activity_log (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts         text NOT NULL,
    category   text,
    action     text,
    target     text,
    detail     text,
    operator   text
);

-- ── 외래키(일괄) ─────────────────────────────────────────────
ALTER TABLE prism_master          ADD CONSTRAINT fk_pm_supplier     FOREIGN KEY (supplier_id)     REFERENCES supplier(id);
ALTER TABLE prism_master          ADD CONSTRAINT fk_pm_painted      FOREIGN KEY (painted_into_id) REFERENCES prism_master(id);
ALTER TABLE product               ADD CONSTRAINT fk_prod_prism      FOREIGN KEY (prism_id)        REFERENCES prism_master(id);
ALTER TABLE receipt               ADD CONSTRAINT fk_rcv_prism       FOREIGN KEY (prism_id)        REFERENCES prism_master(id);
ALTER TABLE receipt               ADD CONSTRAINT fk_rcv_supplier    FOREIGN KEY (supplier_id)     REFERENCES supplier(id);
ALTER TABLE lot                   ADD CONSTRAINT fk_lot_receipt     FOREIGN KEY (receipt_id)      REFERENCES receipt(id);
ALTER TABLE inspection            ADD CONSTRAINT fk_insp_lot        FOREIGN KEY (lot_id)          REFERENCES lot(id);
ALTER TABLE inspection_defect     ADD CONSTRAINT fk_id_insp         FOREIGN KEY (inspection_id)      REFERENCES inspection(id);
ALTER TABLE inspection_defect     ADD CONSTRAINT fk_id_item         FOREIGN KEY (inspection_item_id) REFERENCES inspection_item(id);
ALTER TABLE paint_job             ADD CONSTRAINT fk_pj_lot          FOREIGN KEY (lot_id)          REFERENCES lot(id);
ALTER TABLE paint_return          ADD CONSTRAINT fk_pr_job          FOREIGN KEY (paint_job_id)    REFERENCES paint_job(id);
ALTER TABLE production_plan_line  ADD CONSTRAINT fk_ppl_plan        FOREIGN KEY (plan_id)         REFERENCES production_plan(id);
ALTER TABLE production_plan_line  ADD CONSTRAINT fk_ppl_product     FOREIGN KEY (product_id)      REFERENCES product(id);
ALTER TABLE production_plan_line  ADD CONSTRAINT fk_ppl_prism       FOREIGN KEY (prism_id)        REFERENCES prism_master(id);
ALTER TABLE consumption           ADD CONSTRAINT fk_cons_prism      FOREIGN KEY (prism_id)        REFERENCES prism_master(id);
ALTER TABLE consumption           ADD CONSTRAINT fk_cons_supplier   FOREIGN KEY (supplier_id)     REFERENCES supplier(id);
ALTER TABLE consumption           ADD CONSTRAINT fk_cons_plan       FOREIGN KEY (source_plan_id)  REFERENCES production_plan(id);
ALTER TABLE stock_adjustment      ADD CONSTRAINT fk_adj_prism       FOREIGN KEY (prism_id)        REFERENCES prism_master(id);
ALTER TABLE unusable_stock        ADD CONSTRAINT fk_unusable_prism  FOREIGN KEY (prism_id)        REFERENCES prism_master(id);
ALTER TABLE paint_batch           ADD CONSTRAINT fk_pb_prism        FOREIGN KEY (prism_id)        REFERENCES prism_master(id);
ALTER TABLE paint_batch_defect    ADD CONSTRAINT fk_pbd_batch       FOREIGN KEY (batch_id)        REFERENCES paint_batch(id);
ALTER TABLE paint_batch_defect    ADD CONSTRAINT fk_pbd_item        FOREIGN KEY (inspection_item_id) REFERENCES inspection_item(id);

-- 품목코드는 입력된 경우에만 유일(부분 유니크)
CREATE UNIQUE INDEX IF NOT EXISTS ux_prism_item_code ON prism_master(item_code) WHERE item_code IS NOT NULL;
